import { User, Restaurant } from 'types/index';

/** Dummy user data. */
export const sampleUserData: User[] = [
  { id: 101, name: 'Alice', image: '/images/user.jpg' },
  { id: 102, name: 'Bob', image: '/images/user.jpg' },
  { id: 103, name: 'Caroline', image: '/images/user.jpg' },
  { id: 104, name: 'Dave', image: '/images/user.jpg' },
];

export const sampleRestaurantData: Restaurant[] = [
  {
    id: 1,
    title: 'Vapiano',
    type: 'Restaurant & Cafe',
    marked: true,
    rating: { average: 4.5, count: 2759 },
    image: '/images/vapiano.jpg',
    gallery: [
      '/images/vapiano.jpg',
      '/images/pizza.jpg',
      '/images/breakfast.jpg',
      '/images/salad.jpg',
      '/images/food.jpg',
      '/images/pasta.jpg',
    ],
    tags: ['Bakı', 'Binəqədi R.', '7-ci mikrorayon'],
    menu: [
      {
        type: 'European Cuisine',
        title: 'Pizza',
        items: [
          {
            title: 'Grill Chicken Parmesan',
            description:
              'Garlic Parmesan Sauce, Grilled chicken, ham, tomato, mozzarella cheese, jalapeno',
            price: '15.99 ₼',
            image: '/images/grill_chicken.jpg',
          },
          {
            title: 'American Hot',
            description:
              'Tomato Sauce, Mozzarella, Pepperoni and Jalapeno peppers',
            price: '13.99 ₼',
            image: '/images/american_hot.jpg',
          },
        ],
      },
    ],
    highlights: [
      { title: 'Free Wifi', icon: '' },
      { title: 'Full Service', icon: '' },
      { title: 'Washing-Stand', icon: '' },
      { title: 'Every Hour Cleaning', icon: '' },
    ],
    review: {
      average: 4.5,
      count: 2759,
      stars: {
        5: 1350,
        4: 890,
        3: 500,
        2: 60,
        1: 18,
      },
      items: [
        {
          id: 1,
          user: {
            id: 1,
            name: 'John Doe',
            image: '/images/user.jpg',
          },
          rating: 4.5,
          text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc ut aliquam tincidunt, nunc nisl aliquam massa, eget aliquam nisl nunc vel nisl. Sed euismod, nunc ut aliquam tincidunt, nunc nisl aliquam massa, eget aliquam nisl nunc vel nisl.',
          date: '2020-01-01',
          claps: 10,
        },
        {
          id: 2,
          user: {
            id: 1,
            name: 'John Doe',
            image: '/images/user.jpg',
          },
          rating: 4,
          text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc ut aliquam tincidunt, nunc nisl aliquam massa, eget aliquam nisl nunc vel nisl. Sed euismod, nunc ut aliquam tincidunt, nunc nisl aliquam massa, eget aliquam nisl nunc vel nisl.',
          date: '2020-01-01',
          claps: 5,
        },
      ],
    },
  },
  {
    id: 2,
    title: 'Starbucks',
    type: 'Coffee',
    marked: false,
    rating: { average: 4.1, count: 259 },
    image: '/images/starbucks.jpg',
    tags: ['Coffee', 'Tea', 'Cakes'],
  },
  {
    id: 3,
    title: 'Gloria Jeans',
    type: 'Coffee',
    marked: true,
    rating: { average: 4.1, count: 259 },
    image: '/images/starbucks.jpg',
    tags: ['Coffee', 'Tea', 'Cakes'],
  },
  {
    id: 4,
    title: 'Burger King',
    type: 'Restaurant',
    marked: true,
    rating: { average: 4.5, count: 2759 },
    image: '/images/vapiano.jpg',
    tags: ['Bakı', 'Binəqədi R.', '7-ci mikrorayon'],
  },
  {
    id: 5,
    title: 'Fuzzy',
    type: 'Coffee',
    marked: false,
    rating: { average: 4.1, count: 259 },
    image: '/images/starbucks.jpg',
    tags: ['Coffee', 'Tea', 'Cakes'],
  },
  {
    id: 6,
    title: 'United Coffee',
    type: 'Coffee',
    marked: false,
    rating: { average: 4.1, count: 259 },
    image: '/images/starbucks.jpg',
    tags: ['Coffee', 'Tea', 'Cakes'],
  },
  {
    id: 7,
    title: 'Oz Sut',
    type: 'Restaurant',
    marked: true,
    rating: { average: 4.5, count: 2759 },
    image: '/images/vapiano.jpg',
    tags: ['Bakı', 'Binəqədi R.', '7-ci mikrorayon'],
  },
  {
    id: 8,
    title: 'Coffee House',
    type: 'Coffee',
    marked: false,
    rating: { average: 4.1, count: 259 },
    image: '/images/starbucks.jpg',
    tags: ['Coffee', 'Tea', 'Cakes'],
  },
  {
    id: 9,
    title: 'Taco Bell',
    type: 'Restaurant',
    marked: true,
    rating: { average: 4.5, count: 2759 },
    image: '/images/vapiano.jpg',
    tags: ['Bakı', 'Binəqədi R.', '7-ci mikrorayon'],
  },
  {
    id: 10,
    title: 'Coffee Go',
    type: 'Coffee',
    marked: false,
    rating: { average: 4.1, count: 259 },
    image: '/images/starbucks.jpg',
    tags: ['Coffee', 'Tea', 'Cakes'],
  },
];
